config/routes.rb
Rails.application.routes.draw do
  get 'session/new'

  get 'session/create'

  get 'session/destroy'

  resources :user
  root to: 'home#index'

end

app/models/user.rb
class User
  include Mongoid::Document
  field :username, type: String
  field :password, type: String
  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String
  field :phone, type: String
  field :role, type: String
  field :description, type: String


  class << self
  	# Authentication with bcrypt
    def authentication(user_params)
      user = User.any_of({username: user_params[:username]},{email: user_params[:username]}).try(:first)
      raise if user.blank?
      password = user.password
      if user_params[:password] == password
      	return user
      else
      	return nil
      end
    rescue
      return nil
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	include SessionHelper
  def new
  	redirect_to root_path if is_logged_in?
  end

  def create
    if is_logged_in?
      redirect_to root_path
    end

    user = User.authentication(username: params[:username], password: params[:password])
    session[:user_id] = user.id

    redirect_to root_path

  end

  def destroy
  	session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def show
  end
  
  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/session_helper.rb
# Session helper
# Included on ApplicationController so method on this
# helper can be accessible on all layer
module SessionHelper

  def current_member
    if session[:user_id].present?
      @current_member ||= User.find(session[:user_id])
      # freeze current member to make it immutable (read only)
      @current_member.freeze
    else
      nil
    end
  end

  def is_logged_in?
    current_member.present?
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.slim
// HOME LOGIN

.ml-home
  .container
    .row
      - if is_logged_in?
        .col-sm-12
          = link_to "Logout", session_destroy_path, class: "btn btn-lg btn-block btn-danger text-center"
      - else
        .col-sm-12
          = link_to "Login", session_new_path, class: "btn btn-lg btn-block btn-success text-center"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sales</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/session/create.html.slim
h1 Session#create
p Find me in app/views/session/create.html.slim

app/views/session/destroy.html.slim
h1 Session#destroy
p Find me in app/views/session/destroy.html.slim

app/views/session/new.html.slim
h1 Session#new
= form_tag session_create_path , id:"form_login_only", method: "GET"
  .form-group
    = text_field_tag :username, "", class: "form-control"
  .form-group
    = text_field_tag :password, "", class: "form-control"

  = submit_tag class: "btn btn-primary"

app/views/user/create.html.slim
h1 User#create
p Find me in app/views/user/create.html.slim

app/views/user/destroy.html.slim
h1 User#destroy
p Find me in app/views/user/destroy.html.slim

app/views/user/edit.html.slim
h1 User#edit
p Find me in app/views/user/edit.html.slim

app/views/user/index.html.slim
h1 User#index
p Find me in app/views/user/index.html.slim

app/views/user/new.html.slim
h1 User#new
p Find me in app/views/user/new.html.slim

app/views/user/update.html.slim
h1 User#update
p Find me in app/views/user/update.html.slim